#!/bin/sh

if ! type "xls2txt" >/dev/null; then
  echo 'Please install the xls2txt from https://github.com/vobys/xls2txt'
  exit 1
fi

convert_all_xls() {
  for file in $(git diff --name-status --staged | grep '^A' | grep -Po '[^\t]*$' | grep '.xls'); do
    echo "Converting new file $(basename "$file" .xls).txt"
    xls2txt -A -f "${file}" >"$1/$(basename "$file" .xls).txt"
  done

  for file in $(git diff --name-status --staged | grep '^M' | grep -Po '[^\t]*$' | grep '.xls'); do
    echo "Converting modified file $(basename "$file" .xls).txt"
    xls2txt -A -f "${file}" >"$1/$(basename "$file" .xls).txt"
  done

  for file in $(git diff --name-status --staged | grep '^D' | grep -Po '[^\t]*$' | grep '.xls'); do
    echo "Removing deleted file $(basename "$file" .xls).txt"
    rm -f "$1/$(basename "$file" .xls).txt"
  done

  git add "$1"/
}

convert_all_xls ./txt
